<a href="https://colab.research.google.com/github/Sargam2808/DEEP_LEARNING_LAB/blob/main/dl_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch and Numpy Tensor Basics

In [ ]:
import numpy as np
import torch

Numpy Tensors

In [ ]:
print("NUMPY TENSORS")

np_1d = np.array([1, 2, 3])
np_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D:", np_1d, np_1d.shape)
print("2D:\n", np_2d, np_2d.shape)
print("3D:\n", np_3d, np_3d.shape)


NUMPY TENSORS
1D: [1 2 3] (3,)
2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


Pytorch Tensors

In [ ]:
print("\nPYTORCH TENSORS")

pt_1d = torch.tensor([1, 2, 3])
pt_2d = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
pt_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D:", pt_1d, pt_1d.shape)
print("2D:\n", pt_2d, pt_2d.shape)
print("3D:\n", pt_3d, pt_3d.shape)



PYTORCH TENSORS
1D: tensor([1, 2, 3]) torch.Size([3])
2D:
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])


Element wise operations

In [ ]:
print("\nELEMENT-WISE OPERATIONS")

a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


ELEMENT-WISE OPERATIONS
Addition: tensor([12, 24, 35])
Subtraction: tensor([ 8, 16, 25])
Multiplication: tensor([ 20,  80, 150])
Division: tensor([5., 5., 6.])


Dot product and matrix multiplication

In [ ]:
print("\nDOT PRODUCT")

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

dot_product = torch.dot(x, y)
print("Dot product:", dot_product)

print("\nMATRIX MULTIPLICATION")

A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print("Using matmul:\n", torch.matmul(A, B))
print("Using @ operator:\n", A @ B)



DOT PRODUCT
Dot product: tensor(32)

MATRIX MULTIPLICATION
Using matmul:
 tensor([[19, 22],
        [43, 50]])
Using @ operator:
 tensor([[19, 22],
        [43, 50]])


Indexing and Slicing

In [ ]:
print("\nINDEXING AND SLICING")

t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print("First row:", t[0])
print("Second column:", t[:, 1])
print("Single element:", t[1, 2])

# -------- Boolean Masking --------
print("\nBOOLEAN MASKING")

v = torch.tensor([1, 5, 10, 15, 20])
mask = v > 10

print("Mask:", mask)
print("Filtered values:", v[mask])



INDEXING AND SLICING
First row: tensor([10, 20, 30])
Second column: tensor([20, 50])
Single element: tensor(60)

BOOLEAN MASKING
Mask: tensor([False, False, False,  True,  True])
Filtered values: tensor([15, 20])


Sub tensors

In [ ]:
print("\nSUB-TENSOR")

m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub_tensor = m[0:2, 1:3]
print(sub_tensor)




SUB-TENSOR
tensor([[2, 3],
        [5, 6]])


Reshaping Tensors

In [ ]:
print("\nRESHAPING")

r = torch.tensor([1, 2, 3, 4, 5, 6])

# view() - needs contiguous memory
print("View (2x3):\n", r.view(2, 3))

# reshape() - safer
print("Reshape (3x2):\n", r.reshape(3, 2))

# -------- Unsqueeze --------
u = torch.tensor([1, 2, 3])
print("\nOriginal shape:", u.shape)
print("Unsqueeze dim 0:", u.unsqueeze(0), u.unsqueeze(0).shape)
print("Unsqueeze dim 1:", u.unsqueeze(1), u.unsqueeze(1).shape)



RESHAPING
View (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshape (3x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Original shape: torch.Size([3])
Unsqueeze dim 0: tensor([[1, 2, 3]]) torch.Size([1, 3])
Unsqueeze dim 1: tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


Squeezing

In [ ]:
s = torch.tensor([[1, 2, 3]])
print("\nBefore squeeze:", s.shape)
print("After squeeze:", s.squeeze(), s.squeeze().shape)



Before squeeze: torch.Size([1, 3])
After squeeze: tensor([1, 2, 3]) torch.Size([3])


Numpy reshape

In [ ]:
print("\nNUMPY RESHAPE")

np_r = np.array([1, 2, 3, 4])
print(np_r.reshape(2, 2))


NUMPY RESHAPE
[[1 2]
 [3 4]]


Broadcasting

In [ ]:
print("\nBROADCASTING")

M = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
v = torch.tensor([10, 20, 30])

print("Matrix + Vector:\n", M + v)

x = torch.tensor([[1],
                  [2],
                  [3]])
y = torch.tensor([10, 20, 30])

print("\nColumn + Row:\n", x + y)



BROADCASTING
Matrix + Vector:
 tensor([[11, 22, 33],
        [14, 25, 36]])

Column + Row:
 tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


In place vs out of place operations

In [ ]:

print("\nOUT-OF-PLACE OPERATION")

a = torch.tensor([1, 2, 3])
b = a + 5   # creates new tensor

print("Original a:", a)
print("New b:", b)

print("\nIN-PLACE OPERATION")

a.add_(5)   # modifies existing tensor
print("Modified a:", a)


OUT-OF-PLACE OPERATION
Original a: tensor([1, 2, 3])
New b: tensor([6, 7, 8])

IN-PLACE OPERATION
Modified a: tensor([6, 7, 8])
